### ISSUE TITLE
Deprecate WithPort in favor of just WithAddress

### ISSUE THREAD

**Issue by dylanhitt** [go-fuego/fuego#109]
I read through issue: #101 particularly my comment here: https://github.com/go-fuego/fuego/issues/101#issuecomment-2019215329

WithHost doesn't really give us much. WithAddress covers pretty much everything. WithPort seems a bit redundant at this point. I think we should consider deprecating it for WithAddress.

On the other hand we could deprecate WithAddress in favor of introducing WIthHost to be used alongside WithPort. However I'm in the camp of WithAddress.

My point is that having both WithPort and WithAddress contradict in use. For instance using both options in the same `NewServer` could lead to a unwanted result.

Let me know your thoughts

Cheers!

**Comment by EwenQuim** [comment]
That's true. 
Do you mean just `WithAddr` ?

**Comment by dylanhitt** [comment]
Ah yes,

I will put of the deprecation notice unless you object. PR coming.

**Comment by EwenQuim** [comment]
ok for me !

**Comment by redecs** [comment]
Sorry to revive what seems like a settled issue, but for me the `WithPort` option that was deprecated made a lot of sense because in all the years I used Go I **never** bound a sever to a specific IP address (with micro-services in containers that's doesn't make much sense anyway).

While `WithAddr` is inline with `net/http` I think Fuego could remove some unnecessary friction for most developers using it with the `WithPort` option. 

```go
port := 8080
// instead of 
s := fuego.NewServer(WithAddr(fmt.Sprintf(":%d", port))
// i would do
s := fuego.NewServer(WithPort(port)) 
```

The problem is that the current implementation of `WithPort` binds to localhost only, but the solution there is easy: bind to all address by default as I think most developers do anyway. 

```go
func WithPort(port int) func(*Server) {
	return func(s *Server) { s.Server.Addr = fmt.Sprintf("localhost:%d", port) }
}
// becomes
func WithPort(port int) func(*Server) {
	return func(s *Server) { s.Server.Addr = fmt.Sprintf(":%d", port) }
}
```

Any thoughts?

**Comment by redecs** [comment]
Can you help me understand why you're saying Fuego can't bind to all address implicitly? As I mentioned, I've never bound a specific service to certain IP/host for years now (since I stopped using bare metal servers for hosting multiple applications). With increase usage of containers (ECS, Kubernetes, etc) I see a lot of people doing the same. 

I do understand that there might be a subset of users that will need binding to an address but if those are edge-cases (as it was for me with H2C support) they can leverage the net/http `Server` exposed by Fuego directly (since we don't want to have both `WithAddr` and `WithPort`).

I want to apologise in advance if I missed some obvious point and to thank you for helping me understand the situation better.

**Comment by dylanhitt** [comment]
You can still bind to all addresses?? What I'm saying is fuego shouldn't implicitly do it with a function that doesn't make it clear.

You can still bind all with WithAddr(:8888).
