### ISSUE TITLE
Path param type

### ISSUE THREAD

**Issue by ignishub** [go-fuego/fuego#182]
Can you please tell me how to specify path param type?

**Comment by EwenQuim** [comment]
For now you can't, it's always a string. Go 1.23 router doesn't do any validation anyway so if you call /pets/my-id instead of /pets/123, the router will still match the controller.

We can add type validation on top of that, after # is merged. Just wait a week and this syntax will be available:

```go
fuego.Get(s, "/pets/{id}", getPetByID,
    option.PathInt("id", "ID of the pet to get")
)
```

Security checks:
- Fuego will crash at start time and warn you if the declaration does not match the string in the router
- Fuego will return a HTTPError if the path param "id" is not a string

What do you think about this behaviour? This feature is not merged into main, so you can still have a word about it.

**Comment by EwenQuim** [comment]
In the meantime, you can access the parameters from the route object.

```go
myRoute := fuego.get(s, "/pets/{id}", myController)

myRoute.Operation.Parameters .... = openapi3.TypeInt
```

**Comment by ignishub** [comment]
@EwenQuim 

> In the meantime, you can access the parameters from the route object.
> 
> ```go
> myRoute := fuego.get(s, "/pets/{id}", myController)
> 
> myRoute.Operation.Parameters .... = openapi3.TypeInt
> ```
Thank you! Thats what i looking for! I need that only to generate valid openapi for clients
